# Generated by Django 2.1.7 on 2019-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='messages',
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(to='messaging.GroupMessage'),
        ),
    ]
