# Generated by Django 2.1.7 on 2019-02-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20190227_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='messaging.Author'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to', to='messaging.Author'),
        ),
    ]
