# Generated by Django 2.1.7 on 2019-03-01 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20190227_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='to', to=settings.AUTH_USER_MODEL),
        ),
    ]
