# Generated by Django 2.1.7 on 2019-02-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20190227_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_author_friends_+', to='messaging.Author'),
        ),
    ]
