# Generated by Django 2.1.7 on 2019-03-08 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_groupmessage_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
