# Generated by Django 2.1.7 on 2019-03-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20190301_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default='Fri Mar  1 00:00:00 2019'),
        ),
    ]
