# Generated by Django 2.1.7 on 2019-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
