# Generated by Django 2.1.7 on 2019-03-01 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 1, 15, 18, 37, 917035, tzinfo=utc)),
        ),
    ]
