# Generated by Django 2.1.7 on 2019-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
