# Generated by Django 2.1.7 on 2019-03-01 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20190301_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 1, 15, 52, 49, 671717, tzinfo=utc)),
        ),
    ]
